apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: my-test-gr1
inheritedClusterRoles:
  - cluster-member
  - clusterroletemplatebindings-view
namespacedRules:
  test-ns:
    - apiGroups:
        - ''
      resources:
        - 'configmaps'
      verbs:
        - '*'
